version: '3.7'

services:
  # A docker optimized instance of plex media server 
  plex:
    image: elcrp96/plex-media-server:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=999
      - PGID=995
      - PLEX_PORT=32400
      - VERSION=docker
      - PLEX_CLAIM="" #optional
    volumes:
      - /mnt/storage/local/plex/config:/config # Where you want your Plex Library/Config folder to be
      - /mnt/storage/local/plex/transcode:/transcode # A path for transcoding
      - /mnt/storage/local/plex/transcode/Sync+:/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sync+ # To keep sync transcoding in the transcode folder
      - /mnt/storage/local/plex/transcode/Sync:/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sync   # To keep sync transcoding in the transcode folder
      - /mnt/storage/sync/media:/mnt/media # Media folder
      - /mnt/storage/local/certs/plex/node.pfx:/certs/server.pfx:ro # Certificate File
    restart: unless-stopped
 
  # A proxy based on nginx that sits between the Plex server and
  # the internet. Every time a request is made to Plex, if that
  # request is to mark status, an API call is made
  # to plex-cluster-manager.
  #
  # There is one of these for every Plex server.
  plex-cluster-proxy:
    image: elcrp96/plex-cluster-proxy:latest
    container_name: plex-proxy
    network_mode: host

    environment:
      - PUID=999
      - PGID=995
      - CLUSTER_MANAGER=http://westlea.pates.me.uk:32301
      - CLUSTER_MANAGER_TOKEN=JS6ynqTiczX9rv8g5n4W
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/local/plex-proxy/certs:/certs:ro
      - /mnt/storage/local/plex-proxy/config/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/storage/local/plex-proxy/dhparam/dhparam-2048.pem:/data/dhparam.pem
      - /mnt/storage/local/plex-proxy/logs:/var/log/nginx
      - /mnt/storage/local/plex-proxy/healthcheck.sh:/healthcheck.sh
    ports:
      - 32300:32300
    restart: unless-stopped


services:
  # A docker optimized instance of plex media server 
  plex:
    image: elcrp96/plex-media-server
    container_name: plex
    network_mode: host
    environment:
      - PUID=999
      - PGID=995
      - VERSION=docker
      - PLEX_CLAIM="" #optional
    volumes:
      - /mnt/storage/local/plex/config:/config # Where you want your Plex Library/Config folder to be
      - /mnt/storage/local/plex/transcode:/transcode # A path for transcoding
      - /mnt/storage/local/plex/transcode/Sync+:/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sync+ # To keep sync transcoding in the transcode folder
      - /mnt/storage/local/plex/transcode/Sync:/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sync   # To keep sync transcoding in the transcode folder
      - /mnt/storage/sync/media:/mnt/media # Media folder
      - /mnt/storage/local/certs/plex/node.pfx:/certs/node.pfx:ro # Certificate File
    restart: unless-stopped
 
  # A proxy based on nginx that sits between the Plex server and
  # the internet. Every time a request is made to Plex, if that
  # request is to mark status, an API call is made
  # to plex-cluster-manager.
  #
  # There is one of these for every Plex server.
  plex-cluster-proxy:
    image: elcrp96/plex-cluster-proxy
    container_name: plex-proxy
    network_mode: host

    environment:
      - PUID=999
      - PGID=995
      - CLUSTER_MANAGER=http://westlea.pates.me.uk:3400
      - CLUSTER_MANAGER_TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/local/plex-proxy/certs:/certs:ro
      - /mnt/storage/local/plex-proxy/config/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/storage/local/plex-proxy/dhparam/dhparam-2048.pem:/data/dhparam.pem
      - /mnt/storage/local/plex-proxy/logs:/var/log/nginx
    ports:
      - 32300:32300
    restart: always
